BEGIN;

ALTER TABLE "Chapter"
  ALTER COLUMN "position" TYPE DOUBLE PRECISION USING "position"::DOUBLE PRECISION,
  ALTER COLUMN "positionEnd" TYPE DOUBLE PRECISION USING "positionEnd"::DOUBLE PRECISION;

COMMIT;
